services:
  cpp-devcontainer:
    build:
      context: . # same directory as docker-compose.yml and devcontainer.json
      dockerfile: Dockerfile
    container_name: cpp-devcontainer
    volumes:
      - ..:/workspace
    # demonstrate connectivity between devcontainer and db container
    command: ping -i 10 db
    environment:
      - DEBIAN_FRONTEND=noninteractive
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data:
