services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/cpp:debian-12
    container_name: cpp-devcontainer
    volumes:
      - ../..:/workspaces
    command: sleep infinity
    environment:
      - DEBIAN_FRONTEND=noninteractive
    # depends_on:
    #   - db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data:
