services:
  cpp-devcontainer:
    build:
      context: . # same directory as docker-compose.yml and devcontainer.json
      dockerfile: Dockerfile
    container_name: cpp-devcontainer
    volumes:
      # a) use /workspaces as the root in the container, to create the same directory structure as when a Dockerfile is used (which makes sense)
      # b) the directory names inside the devcontainer are the same as on the local file system
      # - ../..:/workspaces

      # ... or: choose a ${containerWorkspaceFolderBasename}, and hard-code the same value in this compose file and in devcontainer.json
      - ..:/workspaces/myLocalWorkspaceFolderBasename
    # demonstrate connectivity between devcontainer and db container
    command: ping -i 10 db
    environment:
      - DEBIAN_FRONTEND=noninteractive
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    # environment:
      # Uncomment to enable container actions (stop, start, restart). See https://dozzle.dev/guide/actions
      # - DOZZLE_ENABLE_ACTIONS=true
      #
      # Uncomment to allow access to container shells. See https://dozzle.dev/guide/shell
      # - DOZZLE_ENABLE_SHELL=true
      #
      # Uncomment to enable authentication. See https://dozzle.dev/guide/authentication
      # - DOZZLE_AUTH_PROVIDER=simple
volumes:
  postgres-data:
